// import { sociomembresia_pago } from '@prisma/client'

export type PartnerMembershipType = {
    idSocioMembresia: number,
    idEstado: number | null,
    fechaCreacion: Date | null,
    idUsuarioCreo: number | null,
    idSocio: number | null,
    idMembresia: number | null,
    Precio: Decimal | null,
    fechaInicioMembresia: Date | null,
    estadoMembresia: $Enums.sociomembresia_estadoMembresia | null
    meses: number | null,
    semanas: number | null,
    dias: number | null,
    idTipoMembresia: $Enums.sociomembresia_estadoMembresia | null,
    Vencimiento: DateTime,
    ctipomembresia: {
        id: number,
        nombre: string | null,
    } | null,
    membresia: {
        idMembresia: number,
        Nombre: string | null,
        idEstado: number | null,
        fechaCreacion: Date | null,
        Precio: Decimal | null,
        idUsuarioCreo: number | null,
        meses: number | null,
        horaInicio: Date | null,
        horaFinal: Date | null,
        idTipoMembresia: number | null,
        semanas: number | null,
        dias: number | null,
    } | null,
    socio: {
        idSocio: number | null,
        idEstado: number | null,
        fechaCreacion: Date | null,
        Nombre: string | null,
        Paterno: string | null,
        Materno: string | null,
        DNI: string | null,
        Telefono: string | null,
        Observaciones: string | null,
        idUsuarioCreo: number | null,
        // foto: boolean | null,
        // clave: number,
        // huella: boolean | null, /** Duda con este dato */
        fechaNacimiento: Date | null,
        correo: string | null,
        idPlan: number | null,
        blog: boolean | null,
        avanceej: number | null,
        fechamod: Date | null,
        image_profile: string | null,
        nivel: string | null,
        condicionMedica: string | null,
        grupoId: number | null,
        authorization: number | null,
    } | null,
    // sociomembresia_pago: {
    //     id: number,
    //     observacion: string | null,
    //     folio: number | null,
    //     idSocioMembresia: number | null,
    //     fecha: Date | null,
    //     idEstado: number | null,
    //     idUsuarioCreo: number | null,
    //     // importe: Decimal | null,
    // }[] | null
    FechaPago: DateTime
}